<script setup lang="ts">
import { computed, ref } from 'vue'
import { Plus, Search, SlidersHorizontal, Download, MoreHorizontal, X, CheckCircle2, Trash2, Eye, Pencil, ChevronLeft, ChevronRight, Upload, FileText, ShieldCheck, WalletCards } from 'lucide-vue-next'
import type { Role } from '../data'
import { accessFor, canCreate, canDelete, canEdit, canImport } from '../permissions'
const props = defineProps<{ title:string; role:Role }>()
type Row={id:number;primary:string;secondary:string;meta:string;value:string;status:string}
const seed:Record<string,Row[]>={
  'Approval Center':[{id:1,primary:'Anaya Sharma · Admission',secondary:'APR-2026-0421',meta:'Grade 6 · Documents verified',value:'Submitted by Admissions Office',status:'Awaiting approval'},{id:2,primary:'July staff payroll',secondary:'APR-2026-0420',meta:'86 employees · ₹52.8L',value:'Submitted by Finance Admin',status:'Awaiting approval'},{id:3,primary:'Science lab purchase',secondary:'APR-2026-0419',meta:'Equipment procurement · ₹2.4L',value:'Submitted by Ethan Carter',status:'Under review'},{id:4,primary:'Kabir Singh · Admission',secondary:'APR-2026-0418',meta:'Grade 3 · Principal interview complete',value:'Approved 18 Jul',status:'Approved'}],
  Admissions:[{id:1,primary:'Anaya Sharma',secondary:'APP-2026-0148',meta:'Grade 6 · 18 Jul',value:'Parent interview',status:'Under review'},{id:2,primary:'Kabir Singh',secondary:'APP-2026-0147',meta:'Grade 3 · 18 Jul',value:'Documents verified',status:'Approved'},{id:3,primary:'Sara Khan',secondary:'APP-2026-0146',meta:'Grade 8 · 17 Jul',value:'Awaiting birth certificate',status:'Pending'},{id:4,primary:'Vihaan Joshi',secondary:'APP-2026-0145',meta:'Grade 1 · 17 Jul',value:'Entrance assessment',status:'Under review'}],
  People:[{id:1,primary:'Aarav Mehta',secondary:'STU-2026-0842',meta:'Grade 10 A',value:'Guardian: Priya Mehta',status:'Active'},{id:2,primary:'Diya Kapoor',secondary:'STU-2026-0831',meta:'Grade 10 A',value:'Guardian: Rohan Kapoor',status:'Active'},{id:3,primary:'Ethan Carter',secondary:'EMP-0086',meta:'Science Department',value:'Class teacher · 9 B',status:'Active'},{id:4,primary:'Maya Thomas',secondary:'EMP-0079',meta:'Mathematics Department',value:'Senior teacher',status:'On leave'}],
  Academics:[{id:1,primary:'Grade 10 · Section A',secondary:'Class teacher: Maya Thomas',meta:'42 students · English',value:'Room 204',status:'Active'},{id:2,primary:'Grade 9 · Section B',secondary:'Class teacher: Ethan Carter',meta:'38 students · English',value:'Room 112',status:'Active'},{id:3,primary:'Grade 8 · Section A',secondary:'Class teacher: Noah Wilson',meta:'40 students · English',value:'Room 108',status:'Active'},{id:4,primary:'Science · Grade 9',secondary:'Subject code: SCI-09',meta:'6 lessons · 24 topics',value:'Theory + Practical',status:'Published'}],
  Timetable:[{id:1,primary:'Mathematics',secondary:'Maya Thomas',meta:'Grade 10 A',value:'08:30–09:15 · Room 204',status:'Today'},{id:2,primary:'Science',secondary:'Ethan Carter',meta:'Grade 9 B',value:'10:15–11:00 · Lab 2',status:'Today'},{id:3,primary:'English Literature',secondary:'Sophia Miller',meta:'Grade 10 A',value:'11:15–12:00 · Room 204',status:'Today'},{id:4,primary:'Computer Science',secondary:'Liam Davis',meta:'Grade 8 A',value:'13:30–14:15 · IT Lab',status:'Upcoming'}],
  Attendance:[{id:1,primary:'Grade 10 A',secondary:'Marked by Maya Thomas',meta:'40 present · 2 absent',value:'95.2%',status:'Completed'},{id:2,primary:'Grade 9 B',secondary:'Marked by Ethan Carter',meta:'36 present · 2 absent',value:'94.7%',status:'Completed'},{id:3,primary:'Grade 8 A',secondary:'Not marked',meta:'40 students',value:'—',status:'Pending'},{id:4,primary:'Teaching staff',secondary:'19 July 2026',meta:'82 present · 4 absent',value:'95.3%',status:'Completed'}],
  Assignments:[{id:1,primary:'Quadratic Equations',secondary:'Mathematics · Grade 10 A',meta:'Due 21 Jul · 38/42 submitted',value:'100 marks',status:'Review'},{id:2,primary:'Cell Structure Lab Report',secondary:'Science · Grade 9 B',meta:'Due 23 Jul · 26/38 submitted',value:'50 marks',status:'Open'},{id:3,primary:'The Merchant of Venice',secondary:'English · Grade 10 A',meta:'Due 25 Jul · 14/42 submitted',value:'25 marks',status:'Open'},{id:4,primary:'Climate Change Presentation',secondary:'Geography · Grade 8 A',meta:'Closed · 40/40 submitted',value:'20 marks',status:'Graded'}],
  'Exams & Results':[{id:1,primary:'Mid-Term Examination',secondary:'Grades 6–12',meta:'10–18 Sep 2026',value:'Schedule published',status:'Scheduled'},{id:2,primary:'Mathematics Unit Test',secondary:'Grade 10 A',meta:'24 Jul · 09:00',value:'50 marks',status:'Scheduled'},{id:3,primary:'Science Practical',secondary:'Grade 9 B',meta:'28 Jul · Lab 2',value:'30 marks',status:'Draft'},{id:4,primary:'Term I Results',secondary:'Grades 1–5',meta:'Published 12 Jul',value:'96.4% pass rate',status:'Published'}],
  'Fees & Finance':[{id:1,primary:'Aarav Mehta',secondary:'INV-2026-1842',meta:'Term II tuition fee',value:'₹12,500',status:'Due'},{id:2,primary:'Diya Kapoor',secondary:'INV-2026-1839',meta:'Term II tuition fee',value:'₹18,500',status:'Paid'},{id:3,primary:'School transport',secondary:'EXP-2026-0038',meta:'Fuel · July 2026',value:'₹84,200',status:'Approved'},{id:4,primary:'Laboratory supplies',secondary:'EXP-2026-0037',meta:'Science department',value:'₹32,450',status:'Pending'}],
  Announcements:[{id:1,primary:'Annual Sports Day 2026',secondary:'All school',meta:'Published by Olivia Martin',value:'19 Jul · 08:30',status:'Published'},{id:2,primary:'Library maintenance',secondary:'Grades 9–12',meta:'Published by Admin Office',value:'18 Jul · 14:10',status:'Published'},{id:3,primary:'Parent–Teacher Meeting',secondary:'Guardians · Grade 10',meta:'Scheduled by Maya Thomas',value:'22 Jul · 10:00',status:'Scheduled'},{id:4,primary:'Science exhibition entries',secondary:'Grades 6–10',meta:'Draft by Ethan Carter',value:'Not published',status:'Draft'}],
  Messages:[{id:1,primary:'Maya Thomas',secondary:'Re: Aarav’s mathematics progress',meta:'Thank you for checking in. Aarav has…',value:'10 min ago',status:'Unread'},{id:2,primary:'Admin Office',secondary:'Staff meeting agenda',meta:'Please review the attached agenda before…',value:'1 hour ago',status:'Unread'},{id:3,primary:'Priya Mehta',secondary:'Leave request for Aarav',meta:'Aarav will be unable to attend school…',value:'Yesterday',status:'Replied'},{id:4,primary:'Science Department',secondary:'Lab inventory update',meta:'The updated inventory sheet is attached.',value:'17 Jul',status:'Read'}],
  Transport:[{id:1,primary:'Route A · North Delhi',secondary:'Bus DL-01-AB-2486',meta:'Driver: Raj Kumar · 28 stops',value:'42/45 students',status:'On route'},{id:2,primary:'Route B · East Delhi',secondary:'Bus DL-01-AC-1842',meta:'Driver: Sunil Yadav · 22 stops',value:'36/40 students',status:'Completed'},{id:3,primary:'Route C · Central Delhi',secondary:'Bus DL-01-AD-7631',meta:'Driver: Imran Khan · 19 stops',value:'31/35 students',status:'On route'},{id:4,primary:'Route D · West Delhi',secondary:'Bus DL-01-AE-4429',meta:'Driver: Deepak Singh · 25 stops',value:'40/42 students',status:'Delayed'}],
  Library:[{id:1,primary:'The Alchemist',secondary:'Paulo Coelho · BK-01842',meta:'Issued to Aarav Mehta',value:'Due 24 Jul',status:'Issued'},{id:2,primary:'A Brief History of Time',secondary:'Stephen Hawking · BK-00731',meta:'Science · Shelf S-12',value:'3 copies',status:'Available'},{id:3,primary:'To Kill a Mockingbird',secondary:'Harper Lee · BK-00942',meta:'Fiction · Shelf F-08',value:'Due 20 Jul',status:'Overdue'},{id:4,primary:'Oxford School Atlas',secondary:'Oxford Press · BK-01228',meta:'Reference · Shelf R-03',value:'8 copies',status:'Available'}],
  'HR & Payroll':[{id:1,primary:'Ethan Carter',secondary:'EMP-0086 · Science',meta:'26 working days · 1 leave',value:'₹68,500',status:'Processed'},{id:2,primary:'Maya Thomas',secondary:'EMP-0079 · Mathematics',meta:'25 working days · 2 leave',value:'₹74,200',status:'Processed'},{id:3,primary:'Noah Wilson',secondary:'EMP-0068 · Humanities',meta:'26 working days · 0 leave',value:'₹65,800',status:'Pending'},{id:4,primary:'Sophia Miller',secondary:'EMP-0081 · English',meta:'24 working days · 3 leave',value:'₹69,100',status:'Pending'}],
  Reports:[{id:1,primary:'Monthly attendance report',secondary:'Academic · July 2026',meta:'All grades and staff',value:'Updated today',status:'Ready'},{id:2,primary:'Fee collection summary',secondary:'Finance · Term II',meta:'Collected vs outstanding',value:'Updated 1 hour ago',status:'Ready'},{id:3,primary:'Student performance analysis',secondary:'Academic · Term I',meta:'Grades 6–12',value:'Generated 17 Jul',status:'Ready'},{id:4,primary:'Transport occupancy report',secondary:'Operations · July',meta:'All active routes',value:'Generating…',status:'Processing'}],
  Settings:[{id:1,primary:'School profile',secondary:'Identity, contact and affiliation',meta:'Last updated by Olivia Martin',value:'Complete',status:'Configured'},{id:2,primary:'Academic session',secondary:'2026–27 · Term II',meta:'1 Apr 2026–31 Mar 2027',value:'Current',status:'Active'},{id:3,primary:'Roles & permissions',secondary:'14 roles · 86 staff accounts',meta:'RBAC policy v3',value:'Reviewed 2 Jul',status:'Configured'},{id:4,primary:'Notifications & integrations',secondary:'Email, SMS and push channels',meta:'3 providers connected',value:'All operational',status:'Configured'}]
}
const labels:Record<string,[string,string,string,string]>= {'Approval Center':['Approval request','Reference','Submitted by','Decision'],Admissions:['Applicant','Application','Stage','Status'],People:['Person','School ID','Details','Status'],Academics:['Class / Subject','Owner','Details','Status'],Timetable:['Period','Teacher','Time & room','Status'],Attendance:['Class / Group','Recorded by','Attendance','Status'],Assignments:['Assignment','Subject & class','Due / submissions','Status'],'Exams & Results':['Exam','Classes','Schedule','Status'],'Fees & Finance':['Entry','Reference','Amount','Status'],Announcements:['Announcement','Audience','Published','Status'],Messages:['Contact','Subject','Received','Status'],Transport:['Route','Vehicle','Occupancy','Status'],Library:['Book','Author / ID','Availability','Status'],'HR & Payroll':['Employee','Department','Net salary','Status'],Reports:['Report','Category','Updated','Status'],Settings:['Configuration','Scope','Value','Status']}
function roleSeed():Row[]{
 const base=structuredClone(seed[props.title]||[])
 if(props.role==='guardian'){
  if(props.title==='Fees & Finance')return [{id:1,primary:'Aarav Mehta',secondary:'INV-2026-1842',meta:'Term II tuition fee · Due 28 Jul',value:'₹12,500',status:'Due'},{id:2,primary:'Aarav Mehta',secondary:'RCP-2026-1194',meta:'Term I tuition fee · Paid 02 Apr',value:'₹18,500',status:'Paid'},{id:3,primary:'Aarav Mehta',secondary:'RCP-2026-1281',meta:'Transport fee · Paid 05 Jul',value:'₹4,800',status:'Paid'}]
  if(props.title==='Assignments')return [{id:1,primary:'Quadratic Equations',secondary:'Mathematics · Grade 10 A',meta:'Due 21 Jul',value:'Submitted · Awaiting grade',status:'Submitted'},{id:2,primary:'The Merchant of Venice',secondary:'English · Grade 10 A',meta:'Due 25 Jul',value:'Not submitted',status:'Due'},{id:3,primary:'Climate Action Journal',secondary:'Social Science · Grade 10 A',meta:'Due 29 Jul',value:'Not started',status:'Open'}]
  if(props.title==='Exams & Results')return [{id:1,primary:'Mathematics Unit Test',secondary:'Aarav Mehta · Grade 10 A',meta:'18 Jul 2026',value:'46/50 · 92%',status:'Published'},{id:2,primary:'Science Practical',secondary:'Aarav Mehta · Grade 10 A',meta:'12 Jul 2026',value:'27/30 · 90%',status:'Published'},{id:3,primary:'Mid-Term Examination',secondary:'Grade 10 A',meta:'10–18 Sep 2026',value:'Schedule available',status:'Scheduled'}]
  if(props.title==='Transport')return [{id:1,primary:'Aarav Mehta · Route A',secondary:'Bus DL-01-AB-2486',meta:'Driver: Raj Kumar · Stop 14',value:'Pickup 07:18 · Drop 15:42',status:'On route'}]
 }
 if(props.role==='student'){
  if(props.title==='Assignments')return [{id:1,primary:'Quadratic Equations',secondary:'Mathematics · Grade 10 A',meta:'Due 21 Jul · 11:59 PM',value:'Submitted',status:'Submitted'},{id:2,primary:'The Merchant of Venice',secondary:'English · Grade 10 A',meta:'Due 25 Jul · 11:59 PM',value:'Upload response',status:'Due'},{id:3,primary:'Climate Action Journal',secondary:'Social Science · Grade 10 A',meta:'Due 29 Jul',value:'Start assignment',status:'Open'}]
  if(props.title==='Exams & Results')return [{id:1,primary:'Mathematics Unit Test',secondary:'Grade 10 A',meta:'18 Jul 2026',value:'46/50 · Grade A1',status:'Published'},{id:2,primary:'Science Practical',secondary:'Grade 10 A',meta:'12 Jul 2026',value:'27/30 · Grade A1',status:'Published'},{id:3,primary:'Mid-Term Examination',secondary:'Grade 10 A',meta:'10–18 Sep 2026',value:'View schedule',status:'Scheduled'}]
  if(props.title==='Transport')return [{id:1,primary:'My route · Route A',secondary:'Bus DL-01-AB-2486',meta:'Stop 14 · Green Park',value:'Pickup 07:18 · Drop 15:42',status:'On route'}]
  if(props.title==='Library')return [{id:1,primary:'The Alchemist',secondary:'Paulo Coelho · BK-01842',meta:'Issued to you',value:'Due 24 Jul',status:'Issued'},{id:2,primary:'A Brief History of Time',secondary:'Stephen Hawking · BK-00731',meta:'Science · Shelf S-12',value:'3 copies',status:'Available'},{id:3,primary:'Oxford School Atlas',secondary:'Oxford Press · BK-01228',meta:'Reference · Shelf R-03',value:'8 copies',status:'Available'}]
 }
 if(props.role==='teacher'){
  if(props.title==='Assignments')return [{id:1,primary:'Cell Structure Lab Report',secondary:'Science · Grade 9 B',meta:'Due 23 Jul · 26/38 submitted',value:'12 to review',status:'Review'},{id:2,primary:'Human Digestive System',secondary:'Biology · Grade 10 A',meta:'Due 27 Jul · 9/42 submitted',value:'50 marks',status:'Open'},{id:3,primary:'Force and Motion Worksheet',secondary:'Science · Grade 8 A',meta:'Closed · 40/40 submitted',value:'Grading complete',status:'Graded'}]
  if(props.title==='Exams & Results')return [{id:1,primary:'Science Practical',secondary:'Grade 9 B · Teacher: Ethan Carter',meta:'28 Jul · Lab 2',value:'Enter marks',status:'Scheduled'},{id:2,primary:'Biology Unit Test',secondary:'Grade 10 A · Teacher: Ethan Carter',meta:'Completed 17 Jul',value:'34/42 graded',status:'Grading'},{id:3,primary:'Science Term I Results',secondary:'Grade 8 A',meta:'Published 12 Jul',value:'91.2% class average',status:'Published'}]
  if(props.title==='Reports')return [{id:1,primary:'Grade 9 B science performance',secondary:'My class · July 2026',meta:'38 students',value:'Updated today',status:'Ready'},{id:2,primary:'My class attendance',secondary:'Grades 8 A, 9 B, 10 A',meta:'120 students',value:'Updated 1 hour ago',status:'Ready'}]
 }
 return base
}
const storageKey=['superadmin','admin'].includes(props.role)?'edunova-'+props.title:`edunova-${props.role}-${props.title}`
const stored=localStorage.getItem(storageKey)
const rows=ref<Row[]>(stored?JSON.parse(stored):roleSeed())
const mode=accessFor(props.role,props.title)
const query=ref(''), filter=ref('All'), modal=ref<'add'|'view'|'edit'|null>(null), selected=ref<Row|null>(null), toast=ref('')
const form=ref({primary:'',secondary:'',meta:'',value:'',status:'Active'})
const statuses=computed(()=>['All',...new Set(rows.value.map(r=>r.status))])
const filtered=computed(()=>rows.value.filter(r=>(filter.value==='All'||r.status===filter.value)&&Object.values(r).some(v=>String(v).toLowerCase().includes(query.value.toLowerCase()))))
const headers=computed(()=>labels[props.title]||['Record','Reference','Details','Status'])
const statusOptions=computed(()=>props.title==='Admissions'?['Pending','Under review','Documents required','Interview scheduled','Ready for approval','Awaiting approval','Approved','Returned']:props.title==='Assignments'?['Draft','Open','Due','Review','Graded','Published']:props.title==='Exams & Results'?['Draft','Scheduled','Grading','Published']:['Active','Pending','Ready','Published','Completed','Archived'])
const attendanceState=ref<Record<number,string>>({1:'Present',2:'Present',3:'Absent',4:'Late'})
function persist(){localStorage.setItem(storageKey,JSON.stringify(rows.value))}
function openAdd(){form.value={primary:'',secondary:'',meta:'',value:'',status:statusOptions.value[0]};modal.value='add'}
function openView(row:Row){selected.value=row;modal.value='view'}
function openEdit(row:Row){selected.value=row;form.value={primary:row.primary,secondary:row.secondary,meta:row.meta,value:row.value,status:row.status};modal.value='edit'}
function save(){const creating=modal.value==='add';if(creating)rows.value.unshift({id:Date.now(),...form.value});else if(selected.value)Object.assign(selected.value,form.value);persist();modal.value=null;notify(creating?'Record added':'Changes saved')}
function remove(row:Row){if(confirm(`Remove ${row.primary}?`)){rows.value=rows.value.filter(r=>r.id!==row.id);persist();notify('Record removed')}}
function notify(msg:string){toast.value=msg;setTimeout(()=>toast.value='',2200)}
function decide(row:Row,status:string){row.status=status;row.value=status==='Approved'?'Approved by '+(props.role==='superadmin'?'Principal':'Administrator'):'Returned with comments';persist();if(props.title==='Approval Center'&&row.primary.includes('· Admission')){const admissions=JSON.parse(localStorage.getItem('edunova-Admissions')||'[]');const name=row.primary.split(' · ')[0];const application=admissions.find((r:Row)=>r.primary===name);if(application){application.status=status;application.value=row.value;localStorage.setItem('edunova-Admissions',JSON.stringify(admissions))}}notify(status==='Approved'?'Request approved':'Request returned')}
function submitAdmissions(){const candidates=rows.value.filter(r=>r.status==='Ready for approval');if(!candidates.length){notify('Set verified applications to “Ready for approval” first');return}candidates.forEach(r=>r.status='Awaiting approval');persist();const approvalKey='edunova-Approval Center';const existing=localStorage.getItem(approvalKey);const queue=existing?JSON.parse(existing):structuredClone(seed['Approval Center']);candidates.forEach(r=>queue.unshift({id:Date.now()+r.id,primary:r.primary+' · Admission',secondary:r.secondary,meta:r.meta,value:'Submitted by Admissions Office',status:'Awaiting approval'}));localStorage.setItem(approvalKey,JSON.stringify(queue));notify(`${candidates.length} applications sent to Super Admin`)}
function payFee(){const due=rows.value.find(r=>r.status==='Due');if(!due)return;due.status='Paid';due.meta='Paid online · '+new Date().toLocaleDateString();due.value='₹12,500 · Receipt ready';persist();notify('Payment successful · Receipt generated')}
function submitWork(){const due=rows.value.find(r=>r.status==='Due'||r.status==='Open');if(!due){notify('No assignment is awaiting submission');return}due.status='Submitted';due.value='Submitted just now';persist();notify('Assignment submitted successfully')}
function markAttendance(id:number,status:string){attendanceState.value[id]=status;notify(`Attendance marked ${status.toLowerCase()}`)}
function exportCsv(){const csv=[headers.value.join(','),...filtered.value.map(r=>[r.primary,r.secondary,r.meta,r.status].map(v=>'"'+v+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=props.title.toLowerCase().replaceAll(' ','-')+'.csv';a.click();notify('CSV exported')}
</script>
<template><div class="module-view" :class="'mode-'+mode"><div class="page-head"><div><p class="eyebrow">{{title==='Approval Center'?'Governance & oversight':mode==='personal'?'My workspace':mode==='linked'?'Linked child records':'EduNova workspace'}}</p><h1>{{title}}</h1><p>{{rows.length}} {{mode==='personal'||mode==='linked'?'relevant':'school'}} records · {{mode==='oversight'?'Read-only oversight':'Live demo data'}}</p></div><div class="page-actions"><button class="secondary" @click="exportCsv"><Download :size="16"/> Export</button><button v-if="title!=='Approval Center'&&canCreate(role,title)" class="primary" @click="openAdd"><Plus :size="17"/> {{title==='Assignments'?'Create assignment':title==='Announcements'?'New announcement':'Add new'}}</button></div></div>
  <div class="module-metrics"><article><span>Total records</span><strong>{{rows.length}}</strong><small>Current workspace</small></article><article><span>Active / ready</span><strong>{{rows.filter(r=>['Active','Ready','Published','Completed','Configured','Approved','Paid'].includes(r.status)).length}}</strong><small>Up to date</small></article><article><span>Needs attention</span><strong>{{rows.filter(r=>['Pending','Due','Overdue','Delayed','Draft','Unread'].includes(r.status)).length}}</strong><small>Review recommended</small></article></div>
  <div v-if="title==='Admissions'&&role==='admin'" class="approval-banner"><div><ShieldCheck :size="20"/><span><strong>Principal approval workflow</strong><small>Complete document verification and submit eligible applications for final approval.</small></span></div><button class="primary" @click="submitAdmissions">Submit ready applications</button></div>
  <div v-if="title==='Fees & Finance'&&role==='guardian'&&rows.some(r=>r.status==='Due')" class="approval-banner family-action"><div><WalletCards :size="20"/><span><strong>₹12,500 due for Aarav Mehta</strong><small>Term II tuition fee · Due 28 July 2026</small></span></div><button class="primary" @click="payFee">Pay securely</button></div>
  <div v-if="title==='Assignments'&&role==='student'" class="approval-banner family-action"><div><Upload :size="20"/><span><strong>Your next submission is due 25 July</strong><small>The Merchant of Venice · English · Grade 10 A</small></span></div><button class="primary" @click="submitWork">Upload & submit</button></div>
  <article class="data-panel"><div class="table-tools"><div class="table-search"><Search :size="16"/><input v-model="query" :placeholder="'Search '+title.toLowerCase()+'…'"/></div><div class="filter-wrap"><SlidersHorizontal :size="15"/><select v-model="filter"><option v-for="s in statuses" :key="s">{{s}}</option></select></div><button class="secondary compact" @click="notify('Import wizard opened')"><Upload :size="15"/> Import</button></div><div class="table-scroll"><table><thead><tr><th>{{headers[0]}}</th><th>{{headers[1]}}</th><th>{{headers[2]}}</th><th>{{headers[3]}}</th><th></th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id"><td><div class="record-cell"><span>{{row.primary.charAt(0)}}</span><div><strong>{{row.primary}}</strong><small>{{row.secondary}}</small></div></div></td><td>{{row.meta}}</td><td class="value-cell">{{row.value}}</td><td><span :class="['status-pill',row.status.toLowerCase().replaceAll(' ','-')]">{{row.status}}</span></td><td><div class="row-actions"><button v-if="role==='superadmin'&&(title==='Admissions'||title==='Approval Center')&&row.status!=='Approved'" class="approve-action" title="Approve" @click="decide(row,'Approved')"><CheckCircle2 :size="15"/></button><button v-if="role==='superadmin'&&(title==='Admissions'||title==='Approval Center')&&row.status!=='Approved'" class="reject-action" title="Return" @click="decide(row,'Returned')"><X :size="15"/></button><button title="View" @click="openView(row)"><Eye :size="15"/></button><button title="Edit" @click="openEdit(row)"><Pencil :size="15"/></button><button title="Delete" @click="remove(row)"><Trash2 :size="15"/></button></div></td></tr><tr v-if="!filtered.length"><td colspan="5" class="empty-table"><FileText :size="28"/><strong>No matching records</strong><span>Try a different search or filter.</span></td></tr></tbody></table></div><div class="table-footer"><span>Showing {{filtered.length}} of {{rows.length}} records</span><div><button disabled><ChevronLeft :size="14"/></button><button class="current">1</button><button disabled><ChevronRight :size="14"/></button></div></div></article>
  <div v-if="modal" class="modal-backdrop" @click.self="modal=null"><div class="record-modal"><div class="modal-head"><div><p>{{modal==='view'?'RECORD DETAILS':modal==='edit'?'UPDATE RECORD':'NEW RECORD'}}</p><h2>{{modal==='view'?selected?.primary:'Add to '+title}}</h2></div><button @click="modal=null"><X :size="19"/></button></div><template v-if="modal==='view'&&selected"><div class="detail-hero"><span>{{selected.primary.charAt(0)}}</span><div><h3>{{selected.primary}}</h3><p>{{selected.secondary}}</p></div><i :class="['status-pill',selected.status.toLowerCase().replaceAll(' ','-')]">{{selected.status}}</i></div><div class="detail-grid"><div><small>{{headers[1]}}</small><strong>{{selected.meta}}</strong></div><div><small>{{headers[2]}}</small><strong>{{selected.value}}</strong></div><div><small>Record ID</small><strong>#{{selected.id}}</strong></div><div><small>Last updated</small><strong>Today, 10:42 AM</strong></div></div><div class="activity-box"><CheckCircle2 :size="18"/><div><strong>Record is synchronized</strong><p>All authorized roles can see the latest information.</p></div></div><div class="modal-actions"><button class="secondary" @click="modal=null">Close</button><button v-if="canEdit(role,title)" class="primary" @click="openEdit(selected)"><Pencil :size="15"/> Edit record</button></div></template><form v-else @submit.prevent="save"><label>{{headers[0]}}<input v-model="form.primary" required placeholder="Enter name or title"/></label><label>Reference / subtitle<input v-model="form.secondary" required placeholder="Enter reference details"/></label><label>{{headers[1]}}<input v-model="form.meta" required placeholder="Enter details"/></label><label>{{headers[2]}}<input v-model="form.value" required placeholder="Enter value"/></label><label>Status<select v-model="form.status"><option v-for="s in statusOptions" :key="s">{{s}}</option></select></label><div class="modal-actions"><button type="button" class="secondary" @click="modal=null">Cancel</button><button class="primary">{{modal==='edit'?'Save changes':'Create record'}}</button></div></form></div></div><Transition name="toast"><div v-if="toast" class="app-toast"><CheckCircle2 :size="18"/>{{toast}}</div></Transition></div></template>
