<script setup lang="ts">
import { ref } from 'vue'
import { Plus, X, CheckCircle2, Users, BookOpen, CalendarCheck, UserRound, ShieldCheck, Bell, Palette, Database, Globe2, Save, Download, Upload, Plug } from 'lucide-vue-next'
import type { Role } from '../data'
const props=defineProps<{title:string;role:Role}>()
const emit=defineEmits<{navigate:[module:string]}>()
const modal=ref(false),toast=ref(''),tab=ref('Students'),settingsTab=ref('School profile')
const settingsSections=['School profile','Academic setup','Roles & security','Notifications','Branding','Payments & integrations','Data & backups','Localization']
const settingsOptions:Record<string,string[]>={
  'Academic setup':['Continuous assessment','Automatic grade calculation','Teacher lesson approvals','Student promotion workflow'],
  'Roles & security':['Require two-factor authentication','Enforce strong passwords','Maintain audit logs','Auto-lock inactive accounts'],
  Notifications:['Email notifications','SMS alerts','Mobile push notifications','Guardian absence alerts'],
  Branding:['Use school branding','Display school motto','Show school contact details','Use branded exports'],
  'Payments & integrations':['Online fee payments','Payment receipt emails','Zoom classes','Google Workspace sync'],
  'Data & backups':['Nightly encrypted backup','Monthly archive','Export audit logs','Retention policy enforcement'],
  Localization:['English as default language','India Standard Time','Indian number formatting','Show dates as DD/MM/YYYY'],
}
const defaultSettings={
  schoolName:'EduNova Academy',
  affiliation:'CBSE-2730184',
  email:'office@edunova.school',
  phone:'+91 11 4123 8890',
  address:'14 Knowledge Avenue, New Delhi, Delhi 110001',
  logoName:'EduNova mark',
  options:Object.fromEntries(Object.entries(settingsOptions).flatMap(([section,options])=>options.map((option,index)=>[`${section}:${option}`,index!==3]))) as Record<string,boolean>,
}
function readSettings(){
  try{return {...defaultSettings,...JSON.parse(localStorage.getItem('edunova:settings')||'{}'),options:{...defaultSettings.options,...JSON.parse(localStorage.getItem('edunova:settings')||'{}').options}}}
  catch{return structuredClone(defaultSettings)}
}
const settings=ref(readSettings())
const backupInput=ref<HTMLInputElement|null>(null)
const accounts=ref([{name:'Aarav Mehta',type:'Student',id:'STU-2026-0842',link:'Priya Mehta · Guardian',status:'Active'},{name:'Ethan Carter',type:'Teacher',id:'EMP-0086',link:'Grade 9 B · Science',status:'Active'},{name:'Priya Mehta',type:'Guardian',id:'PAR-0241',link:'Aarav Mehta · Grade 10 A',status:'Active'}])
const form=ref({name:'',type:'Student',email:'',link:''})
const classes=[{name:'Grade 9 B',subject:'Science',students:38,next:'Today · 10:15 AM',progress:68},{name:'Grade 10 A',subject:'Biology',students:42,next:'Tomorrow · 08:30 AM',progress:74},{name:'Grade 8 A',subject:'Science',students:40,next:'Wed · 11:15 AM',progress:51}]
const classDetail=ref<(typeof classes)[number]|null>(null)
function notify(s:string){toast.value=s;setTimeout(()=>toast.value='',2200)}
function createAccount(){accounts.value.unshift({name:form.value.name,type:form.value.type,id:(form.value.type==='Teacher'?'EMP':'ACC')+'-'+Date.now().toString().slice(-5),link:form.value.link,status:'Invitation sent'});modal.value=false;notify('Account created and invitation sent');form.value={name:'',type:'Student',email:'',link:''}}
function saveSettings(){localStorage.setItem('edunova:settings',JSON.stringify(settings.value));notify('All settings saved')}
function exportBackup(){
 const data:Record<string,string>={}
 for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith('edunova'))data[key]=localStorage.getItem(key)||''}
 const link=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify({version:1,createdAt:new Date().toISOString(),data},null,2)],{type:'application/json'}))
 link.href=url;link.download=`edunova-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);notify('Encrypted-ready backup exported')
}
async function restoreBackup(event:Event){
 const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return
 try{const backup=JSON.parse(await file.text());if(!backup.data||typeof backup.data!=='object')throw new Error('Invalid backup');Object.entries(backup.data).forEach(([key,value])=>{if(key.startsWith('edunova'))localStorage.setItem(key,String(value))});settings.value=readSettings();notify('Backup restored successfully')}
 catch{notify('Backup file is not valid')}
 input.value=''
}
</script>
<template><div><div class="page-head"><div><p class="eyebrow">{{title==='Settings'?'Institution configuration':'Role workspace'}}</p><h1>{{title}}</h1><p>{{title==='User Accounts'?'Provision identities and connect school relationships.':title==='My Classes'?'Your teaching assignments for 2026–27.':title==='My Children'?'Linked learner profiles and progress.':title==='My Learning'?'Your subjects, progress and learning plan.':'Manage school-wide preferences and security.'}}</p></div><button v-if="title==='User Accounts'" class="primary" @click="modal=true"><Plus :size="16"/> Create account</button><button v-if="title==='Settings'" class="primary" @click="saveSettings"><Save :size="16"/> Save changes</button></div>
<template v-if="title==='User Accounts'"><div class="account-tabs"><button v-for="t in ['Students','Teachers','Guardians','Administrators']" :class="{active:tab===t}" @click="tab=t">{{t}}</button></div><article class="account-board"><div class="account-head"><span>Account holder</span><span>Role</span><span>Linked to / assignment</span><span>Status</span></div><div v-for="a in accounts.filter(a=>tab.startsWith(a.type))" class="account-row"><div><span class="student-avatar">{{a.name[0]}}</span><span><strong>{{a.name}}</strong><small>{{a.id}}</small></span></div><span>{{a.type}}</span><strong>{{a.link}}</strong><span class="status-pill active">{{a.status}}</span></div><div v-if="!accounts.filter(a=>tab.startsWith(a.type)).length" class="role-empty">No demo accounts in this category. Use “Create account” to add one.</div></article></template>
<template v-else-if="title==='My Classes'"><div class="class-grid"><article v-for="c in classes"><div class="class-color"></div><span>{{c.subject}}</span><h3>{{c.name}}</h3><p><Users :size="14"/>{{c.students}} students</p><div class="class-progress"><span><i :style="{width:c.progress+'%'}"></i></span><small>{{c.progress}}% syllabus complete</small></div><div class="class-next"><CalendarCheck :size="16"/><span><small>Next class</small><strong>{{c.next}}</strong></span></div><div class="class-actions"><button @click="classDetail=c">View roster</button><button @click="emit('navigate','Assignments')">Create assignment</button></div></article></div></template>
<template v-else-if="title==='My Learning'"><div class="student-overview"><article><span class="profile-avatar">AM</span><div><h2>Aarav Mehta</h2><p>Grade 10 A · Roll 01 · STU-2026-0842</p></div><span class="status-pill active">Active</span></article><div class="learning-stats"><span><b>88%</b><small>Overall average</small></span><span><b>96%</b><small>Attendance</small></span><span><b>3</b><small>Assignments due</small></span><span><b>12th</b><small>Class rank</small></span></div></div><div class="subject-grid"><article v-for="(s,i) in ['Mathematics','Science','English','Computer Science']"><BookOpen :size="20"/><strong>{{s}}</strong><span>{{[91,87,84,92][i]}}% average</span><button @click="emit('navigate','Assignments')">Open coursework</button></article></div></template>
<template v-else-if="title==='My Children'"><div class="child-card"><div><span class="profile-avatar">AM</span><span><h2>Aarav Mehta</h2><p>Grade 10 A · Roll 01</p></span><span class="status-pill active">Active</span></div><div class="learning-stats"><span><b>88%</b><small>Average score</small></span><span><b>96%</b><small>Attendance</small></span><span><b>₹12,500</b><small>Fee due</small></span><span><b>3</b><small>Tasks due</small></span></div><div class="child-actions"><button @click="emit('navigate','Exams & Results')">View report card</button><button @click="emit('navigate','Messages')">Message class teacher</button><button @click="emit('navigate','Fees & Finance')">Pay fees</button></div></div></template>
<template v-else><div class="settings-layout"><aside><button v-for="(s,i) in settingsSections" :class="{active:settingsTab===s}" @click="settingsTab=s"><component :is="[UserRound,BookOpen,ShieldCheck,Bell,Palette,Plug,Database,Globe2][i]" :size="16"/>{{s}}</button></aside><article class="settings-form"><h2>{{settingsTab}}</h2><p>{{settingsTab==='School profile'?'Official institution identity and contact information.':'Configure '+settingsTab.toLowerCase()+' for EduNova Academy.'}}</p><template v-if="settingsTab==='School profile'"><div class="settings-logo"><span>EA</span><div><strong>School logo</strong><small>{{settings.logoName}} · PNG or JPG · Maximum 2 MB</small><button type="button" @click="settings.logoName='Updated school logo';notify('School logo updated')">Change logo</button></div></div><div class="settings-grid"><label>School name<input v-model="settings.schoolName"/></label><label>Affiliation number<input v-model="settings.affiliation"/></label><label>Official email<input v-model="settings.email" type="email"/></label><label>Phone number<input v-model="settings.phone"/></label><label class="full">School address<textarea v-model="settings.address"></textarea></label></div></template><template v-else><div class="setting-options"><label v-for="(option,i) in settingsOptions[settingsTab]" :key="option"><span><strong>{{option}}</strong><small>{{i%2?'Applies to authorized staff':'Recommended configuration'}}</small></span><input v-model="settings.options[`${settingsTab}:${option}`]" type="checkbox"/></label></div><div v-if="settingsTab==='Data & backups'" class="backup-actions"><input ref="backupInput" class="visually-hidden" type="file" accept=".json,application/json" @change="restoreBackup"/><button class="secondary" @click="exportBackup"><Download :size="15"/> Export full backup</button><button class="secondary" @click="backupInput?.click()"><Upload :size="15"/> Restore backup</button></div></template></article></div></template>
<div v-if="classDetail" class="modal-backdrop" @click.self="classDetail=null"><div class="class-roster-modal"><div class="modal-head"><div><p>ASSIGNED CLASS</p><h2>{{classDetail.name}} · {{classDetail.subject}}</h2></div><button @click="classDetail=null"><X :size="18"/></button></div><div class="roster-summary"><span><b>{{classDetail.students}}</b><small>Students</small></span><span><b>{{classDetail.progress}}%</b><small>Syllabus</small></span><span><b>94.7%</b><small>Attendance</small></span></div><div class="mini-roster"><div v-for="(student,i) in ['Aarav Mehta','Diya Kapoor','Ishaan Verma','Sara Khan']"><span class="student-avatar">{{student[0]}}</span><span><strong>{{student}}</strong><small>Roll {{String(i+1).padStart(2,'0')}}</small></span><button @click="classDetail=null;emit('navigate','Messages')">Message</button></div></div><div class="modal-actions"><button class="secondary" @click="classDetail=null">Close</button><button class="primary" @click="classDetail=null;emit('navigate','Attendance')">Take attendance</button></div></div></div><div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="task-modal" @submit.prevent="createAccount"><div class="modal-head"><div><p>IDENTITY PROVISIONING</p><h2>Create school account</h2></div><button type="button" @click="modal=false"><X :size="18"/></button></div><label>Account type<select v-model="form.type"><option>Student</option><option>Teacher</option><option>Guardian</option><option>Administrator</option></select></label><label>Full name<input v-model="form.name" required placeholder="Enter legal name"/></label><label>Email / login ID<input v-model="form.email" required type="email" placeholder="name@example.com"/></label><label>{{form.type==='Guardian'?'Linked student':form.type==='Teacher'?'Assigned class & subject':'Relationship / assignment'}}<input v-model="form.link" required placeholder="e.g. Aarav Mehta · Grade 10 A"/></label><div class="modal-actions"><button type="button" class="secondary" @click="modal=false">Cancel</button><button class="primary">Create & invite</button></div></form></div><Transition name="toast"><div v-if="toast" class="app-toast"><CheckCircle2 :size="18"/>{{toast}}</div></Transition></div></template>
