<script setup lang="ts">
import { computed, ref } from 'vue'
import { Plus, Search, ChevronLeft, ChevronRight, CheckCircle2, X, Send } from 'lucide-vue-next'
import type { Role } from '../data'
const props=defineProps<{title:string;role:Role}>()
const toast=ref(''),modal=ref(false),query=ref(''),message=ref('')
const weekIndex=ref(0)
const weekLabel=computed(()=>weekIndex.value===0?'20–24 July 2026':weekIndex.value<0?'13–17 July 2026':'27–31 July 2026')
const selectedMessage=ref<string[]|null>(null),reply=ref('')
const folder=ref('Inbox')
const attendance=ref<Record<number,string>>({1:'Present',2:'Present',3:'Absent',4:'Late',5:'Present'})
const students=['Aarav Mehta','Diya Kapoor','Ishaan Verma','Sara Khan','Vihaan Joshi']
const periods=ref([['Mathematics','Maya Thomas','Room 204'],['Science','Ethan Carter','Lab 2'],['English Literature','Sophia Miller','Room 204'],['Computer Science','Liam Davis','IT Lab']])
const roleMessages:Record<Role,string[][]>={superadmin:[['Olivia Martin','Weekly operations summary','Admissions, attendance and fee operations are on track.','10 min'],['Finance Office','Payroll approval required','July payroll is ready for principal approval.','1 hr'],['School Board','Governance meeting','The board agenda and supporting papers are attached.','Yesterday']],admin:[['Dr. James Wilson','Admission approval returned','Please review the principal’s comments on the application.','10 min'],['Priya Mehta','Leave request for Aarav','Aarav will be unable to attend school on Friday.','1 hr'],['Ethan Carter','Science lab request','The purchase request is ready for administrative review.','Yesterday']],teacher:[['Priya Mehta','Aarav’s science progress','Could you share an update on Aarav’s recent work?','10 min'],['Admin Office','Staff meeting agenda','Please review the attached agenda before tomorrow.','1 hr'],['Grade 9 B','Assignment question','Several students asked about the lab report format.','Yesterday']],student:[['Maya Thomas','Mathematics feedback','Excellent improvement in your recent assessment.','10 min'],['Ethan Carter','Lab report reminder','Please submit your lab report before 11:59 PM.','1 hr'],['Library Desk','Book due reminder','The Alchemist is due on 24 July.','Yesterday']],guardian:[['Maya Thomas','Aarav’s mathematics progress','Aarav has shown excellent improvement this month.','10 min'],['Admin Office','Parent–teacher meeting','Please confirm attendance for Saturday’s meeting.','1 hr'],['Transport Desk','Route A timing update','Tomorrow’s pickup will be ten minutes earlier.','Yesterday']]}
const messages=computed(()=>roleMessages[props.role])
const folderMessages=computed(()=>folder.value==='Inbox'?messages.value:folder.value==='Sent'?[['You','Progress update sent','Your message was delivered successfully.','Yesterday']]:folder.value==='Drafts'?[['Draft','Science fair follow-up','Continue writing this draft message.','Today']]:[])
const recipients=computed(()=>({superadmin:['Olivia Martin · Administrator','School Board','All administrators'],admin:['Dr. James Wilson · Principal','All staff','Selected guardian'],teacher:['Grade 9 B · Students & guardians','Priya Mehta · Guardian','Admin Office'],student:['Maya Thomas · Class teacher','Ethan Carter · Science','School support'],guardian:['Maya Thomas · Class teacher','Admin Office','Transport Desk']} as Record<Role,string[]>)[props.role])
function notify(text:string){toast.value=text;setTimeout(()=>toast.value='',2200)}
function saveAttendance(){localStorage.setItem('edunova-attendance-demo',JSON.stringify(attendance.value));notify('Attendance saved · Guardian alerts sent')}
function send(){if(!message.value.trim())return;message.value='';modal.value=false;notify('Message sent successfully')}
function sendReply(){if(!reply.value.trim())return;reply.value='';notify('Reply sent')}
function saveModal(){if(props.title==='Messages'){send();return}if(props.title==='Timetable')periods.value.push([message.value,'Assigned teacher','Room TBD']);message.value='';modal.value=false;notify(props.title==='Timetable'?'Period added to timetable':'Attendance note saved')}
</script>
<template><div class="special-module"><div class="page-head"><div><p class="eyebrow">EduNova workspace</p><h1>{{title}}</h1><p>{{title==='Timetable'?'Weekly academic schedule':title==='Attendance'?'Daily student attendance':'School communication center'}}</p></div><button v-if="title==='Messages'||(['Timetable','Attendance'].includes(title)&&['admin','teacher'].includes(role))" class="primary" @click="modal=true"><Plus :size="16"/>{{title==='Messages'?'Compose':title==='Timetable'?'Add period':'Attendance note'}}</button></div>
<template v-if="title==='Timetable'"><div class="timetable-top"><div><button @click="weekIndex--"><ChevronLeft :size="15"/></button><button @click="weekIndex=0">Today</button><button @click="weekIndex++"><ChevronRight :size="15"/></button></div><strong>{{weekLabel}}</strong><select v-if="['admin','superadmin'].includes(role)"><option>All classes</option><option>Grade 10 A</option><option>Grade 9 B</option></select><span v-else class="schedule-owner">{{role==='teacher'?'My assigned classes':role==='guardian'?'Aarav · Grade 10 A':'Grade 10 A · My timetable'}}</span></div><article class="week-board"><div class="time-column"><b>TIME</b><span v-for="t in ['08:30','09:15','10:15','11:15']">{{t}}</span></div><div v-for="(day,di) in ['MON 20','TUE 21','WED 22','THU 23','FRI 24']" class="day-column"><b>{{day}}</b><button v-for="(p,pi) in periods" :class="'schedule-tone-'+((di+pi)%4)" @click="notify(p[0]+' · '+p[1]+' · '+p[2])"><strong>{{p[0]}}</strong><span>{{p[1]}}</span><small>{{p[2]}}</small></button></div></article></template>
<template v-else-if="title==='Attendance'"><template v-if="['student','guardian'].includes(role)"><div class="personal-attendance"><article><span>96%</span><div><strong>{{role==='guardian'?'Aarav’s attendance':'Your attendance'}}</strong><p>Excellent standing · 2 absences this term</p></div></article><div class="month-attendance"><div class="month-head"><strong>July 2026</strong><span><i class="dot-present"></i>Present <i class="dot-absent"></i>Absent</span></div><div class="attendance-calendar"><b v-for="d in ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']">{{d}}</b><span v-for="n in 31" :class="{absent:n===8||n===17,holiday:n%7===6||n%7===0}">{{n}}</span></div></div><article class="attendance-history"><h3>Recent attendance</h3><div v-for="r in [['20 Jul','Present','08:12 AM'],['19 Jul','Present','08:08 AM'],['18 Jul','Present','08:15 AM'],['17 Jul','Absent','Medical leave']]" :class="r[1].toLowerCase()"><strong>{{r[0]}}</strong><span>{{r[1]}}</span><small>{{r[2]}}</small></div></article></div></template><template v-else><div class="attendance-controls"><div><select><option>Grade 10 A</option><option>Grade 9 B</option></select><input type="date" value="2026-07-20"/></div><div><span class="count-present">{{Object.values(attendance).filter(v=>v==='Present').length}} Present</span><span class="count-absent">{{Object.values(attendance).filter(v=>v==='Absent').length}} Absent</span><button class="primary" @click="saveAttendance">Save & notify</button></div></div><article class="roster-card"><div class="roster-head"><span>Student</span><span>Roll number</span><span>Attendance status</span></div><div v-for="(student,i) in students" class="roster-row"><div><span class="student-avatar">{{student[0]}}</span><strong>{{student}}</strong></div><span>#{{String(i+1).padStart(2,'0')}}</span><div><button v-for="s in ['Present','Absent','Late','Excused']" :class="{selected:attendance[i+1]===s}" @click="attendance[i+1]=s">{{s}}</button></div></div></article></template></template>
<template v-else><article class="inbox"><aside><button class="primary" @click="modal=true"><Plus :size="15"/> New message</button><button v-for="f in ['Inbox','Sent','Drafts','Archived']" :class="{active:folder===f}" @click="folder=f;selectedMessage=null"><span>{{f}}</span><span v-if="f==='Inbox'">2</span><span v-if="f==='Drafts'">1</span></button></aside><section v-if="!selectedMessage"><div class="inbox-search"><Search :size="16"/><input v-model="query" :placeholder="'Search '+folder.toLowerCase()+'…'"/></div><button v-for="(m,i) in folderMessages.filter(m=>m.join(' ').toLowerCase().includes(query.toLowerCase()))" :class="{unread:folder==='Inbox'&&i<2}" @click="selectedMessage=m"><span class="student-avatar">{{m[0][0]}}</span><span><strong>{{m[0]}}</strong><b>{{m[1]}}</b><small>{{m[2]}}</small></span><time>{{m[3]}}</time></button><div v-if="!folderMessages.length" class="message-empty"><CheckCircle2 :size="26"/><strong>No {{folder.toLowerCase()}} messages</strong><span>This folder is currently empty.</span></div></section><section v-else class="conversation"><div class="conversation-head"><button @click="selectedMessage=null">← {{folder}}</button><div><strong>{{selectedMessage[1]}}</strong><span>{{selectedMessage[0]}} · {{selectedMessage[3]}}</span></div></div><div class="thread"><div class="message-bubble incoming"><strong>{{selectedMessage[0]}}</strong><p>{{selectedMessage[2]}} I wanted to share this update with you and check whether you have any questions.</p><small>{{selectedMessage[3]}}</small></div><div class="message-bubble outgoing"><strong>You</strong><p>Thank you for the update. I have reviewed the information.</p><small>Just now</small></div></div><form class="reply-box" @submit.prevent="sendReply"><textarea v-model="reply" required placeholder="Write a reply…"></textarea><button class="primary"><Send :size="15"/> Send reply</button></form></section></article></template>
<div v-if="modal" class="modal-backdrop" @click.self="modal=false"><form class="task-modal" @submit.prevent="saveModal"><div class="modal-head"><div><p>CREATE NEW</p><h2>{{title==='Messages'?'Compose message':title==='Timetable'?'Add timetable period':'Add attendance note'}}</h2></div><button type="button" @click="modal=false"><X :size="18"/></button></div><label v-if="title==='Messages'">Recipient<select><option v-for="recipient in recipients" :key="recipient">{{recipient}}</option></select></label><label>{{title==='Messages'?'Message':title==='Timetable'?'Subject / period name':'Attendance note'}}<textarea v-model="message" required placeholder="Enter details…"></textarea></label><div class="modal-actions"><button type="button" class="secondary" @click="modal=false">Cancel</button><button class="primary"><Send :size="14"/> Save</button></div></form></div><Transition name="toast"><div v-if="toast" class="app-toast"><CheckCircle2 :size="18"/>{{toast}}</div></Transition></div></template>
